---
# file: plays/reset_hub.yml

- hosts: all
- tasks:
  - name: Stop dream services
    systemd: name={{ item }} state=stopped enabled=True
    with_items:
      - dream-batcher
      - dream-sniffer
      - dream-syncer

  - name: Restart redis
    systemd: name= state=restarted

  - name: Flush all from redis
    redis:
      command: flush
      flush_mode: all
  
  - name: Reset sqlite
    command: /usr/local/sobun/bin/reset_sqllite.sh

  - name: Start dream services
      systemd: name={{ item }} state=started enabled=True
    with_items:
      - dream-batcher
      - dream-sniffer
      - dream-syncer

