---
# file: plays/provision_hub.yml
- hosts: all
  vars:
    hub_hostname: unclaimed_hub
    hub_user: pi
    hub_group: pi
    hub_google_project_id: unknown
    hub_google_pubsub_topic: unknown
    hub_batch_size: 20000
    hub_dream_pubsub_timeout: unknown
    hub_google_application_credentials: unknown
    ansible_python_interpreter: python3

  pre_tasks:
    - name: Ensure this users ssh-id is added to remote $hub_user authorized_keys (you probably want to ssh-add secrets/hub_credentials/hub_default)
      authorized_key:
        user: "{{ hub_user }}"
        state: present
        key: "{{ lookup('file', '../../../secrets/hub_credentials/hub_default.pub') }}"
    - name: Update all packages (if you cared about the version, you should specify it in the play)
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles: 
    - ../roles/hub_common
    - ../roles/hub_redis
    - ../roles/hub_sqlite
    - ../roles/hub_code
    - ../roles/hub_config
    - ../roles/hub_services
  
  post_tasks:
      - name: Reboot hub
        reboot:
          reboot_timeout: 60
      - name: "Completed"
        debug:
          msg: "{{ hub_hostname }} has been provisioned, you may deploy code changes using update_hub.yml for a faster experience"