---
# file: roles/hub_base/tasks/main.yml
- name: Set hostname
  hostname: 
    name: "{{ hub_hostname }}"

- name: Manage /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  
- name: Remove unwanted packages
  apt: name="wolfram-engine" state=absent
  
- name: Install upstream prerequisites
  apt: name="{{ packages }}" state=present
  vars:
    packages:
        - libglib2.0-dev
        - time
        - speedtest-cli
        - wondershaper
        - python3
        - python3-pip
 
- name: Install python dependencies
  pip: name="{{ packages }}" executable=pip3
  vars:
    packages:
        - python-daemon
        - bluepy

# This should work, instead the next task will just shell out to do it 
#- name: Set net_raw capability on bluepi helper so it can run as non-root
#  capabilities:
#    path: /usr/local/lib/python3.5/dist-packages/bluepy/bluepy-helper
#    capability: ["cap_net_raw","cap_net_admin+eip"]
#    state: present

- name: Set net_raw and net_admin capabilities on bluepy-helper so that sniffer can start
  command: /sbin/setcap cap_net_admin,cap_net_raw+eip /usr/local/lib/python3.5/dist-packages/bluepy/bluepy-helper

- name: Set memory overcommit
  sysctl:
    name: vm.overcommit_memory
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Configure logrotate
  copy:
    src: logrotate.conf
    dest: /etc/logrotate.conf
