---
# file: roles/hub_code/tasks/main.yml

- name: Create code directories
  file:
    path: "{{item}}"
    state: directory
    owner: "{{ hub_user }}"
    group: "{{ hub_group }}"
    mode: 0750
  with_items:
    - /usr/local/sobun
    - /usr/local/sobun/config
    - /usr/local/sobun/helpers

- name: Copy sobun directory from this project
  synchronize:
    src: ../../../../sobun
    dest: /usr/local

- name: Set recursive ownership of synced files
  file:
    path: /usr/local/sobun
    owner: "{{ hub_user }}"
    group: "{{ hub_group }}"
    recurse: True

- name: Copy requirements.txt
  copy: src=../../../../sobun/requirements.txt dest=/usr/local/sobun/requirements.txt

- name: Install our system level requirements not specified in sobuns/requirements.txt
  pip:
    executable: pip3
    name:
        - bluepy
        - google-cloud-pubsub

- name: Install sobun specific prerequisites
  pip:
    executable: pip3
    requirements: /usr/local/sobun/requirements.txt

- name: Ensure there is an empty measurements.db
  file: name=/usr/local/sobun/measurements.db state=touch owner={{ hub_user }} group={{ hub_group }} mode=0660

- name: Have dream.batcher initialize the db
  command: /usr/bin/python3 -m dream.batcher --reset
  args:
    chdir: /usr/local/sobun
