---
# file: roles/hub_code/tasks/main.yml

- name: Create code directories
  file:
    path: "{{item}}"
    state: directory
    owner: "{{ hub_user }}"
    group: "{{ hub_group }}"
    mode: 0750
  with_items:
    - /usr/local/sobun
    - /usr/local/sobun/config
    - /usr/local/sobun/helpers

- name: Ensure there is an empty measurements.db
  file: name=/usr/local/sobun/measurements.db state=touch owner={{ hub_user }} group={{ hub_group }} mode=0640
    
- name: Copy sobun directory from this project
  copy: src=../../../../sobun dest=/usr/local owner={{ hub_user }} group={{ hub_group }}

- name: Copy requirements.txt
  copy: src=../../../../sobun/requirements.txt dest=/usr/local/sobun/requirements.txt

- name: Install sobun specific prerequisites
  pip:
    requirements: /usr/local/sobun/requirements.txt
