---
# file: roles/hub_services/tasks/main.yml
- name: Manage systemd service and timer files
  copy: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - dream-batcher.service
    - dream-sniffer@.service
    - dream-syncer.service

- name: Start services
  systemd: name={{ item }} state=started enabled=True
  with_items:
    - redis
    - dream-batcher
    - dream-syncer
    - dream-sniffer@0
    - dream-sniffer@1
    - dream-sniffer@2
    - dream-sniffer@3
